# Generated by Django 5.0.2 on 2024-02-29 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('codeclass', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelleclass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('codeFrais', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('codeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paiement.classe')),
            ],
        ),
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepaie', models.CharField(max_length=20)),
                ('montant', models.CharField(max_length=10)),
                ('codeFrais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paiement.frais')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paiement.eleve')),
            ],
        ),
    ]
